apiVersion: v1
kind: Service
metadata:
  name: load-balancer
  namespace: microstack
spec:
  type: NodePort
  selector:
    app: load-balancer
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30007